---
title: "Question 2"
author: "Ricky Melo, 22090685"
date: "2025-05-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
SleepCogStudy <- read.csv("Resources/Sleep_Cognition_Study_f1PhaXA.csv")
```

### Test whether gender is independent of nap frequency.

```{r}
# Inital Table
table(SleepCogStudy$Gender, SleepCogStudy$NapFrequency)
genderTable = matrix(c(43,41,33,38,28,27,28,47,1,1,2,4,2,1,2,2), ncol = 4)

dimnames(genderTable) = list(gender = c("Female","Male","Non-Binary", "Other"), 
                             napFrequency = c("Never", "Often","Rarely", "Sometimes"))

barplot(genderTable, col = c("pink", "skyblue", "yellow", "brown"), beside = TRUE, legend = rownames(genderTable),
        main = "Nap Frequency by Gender",
        xlab = "Nap Frequency",
        ylab = "Count")   
```


```{r}
# H0: Gender is independent of nap frequency
# HA: Gender is dependent of nap frequency

# Expected Values
gender.count = rowSums(genderTable)
napFrequency.counts = colSums(genderTable)
outer(gender.count, napFrequency.counts) / sum(genderTable)

# Test independence of gender on nap frequency
chisq.test(genderTable, simulate.p.value = TRUE)
# p-value = 0.5662 

# Conclusion:
# As the p-value is greater than 0.05
# we do not reject the null hypothesis
```



